// <auto-generated />
using EzBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzBooking.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107120115_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EzBooking.Models.House", b =>
                {
                    b.Property<int>("id_house")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_house"), 1L, 1);

                    b.HasKey("id_house");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("EzBooking.Models.PostalCode", b =>
                {
                    b.Property<int>("postalCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("postalCode"), 1L, 1);

                    b.HasKey("postalCode");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("EzBooking.Models.StatusHouse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.HasKey("id");

                    b.ToTable("StatusHouses");
                });
#pragma warning restore 612, 618
        }
    }
}
